# -*- coding: utf-8 -*-
"""Rodriquez.Anecia-PythonCode-ITT103-F2023.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1976ghFE9qRJopVmbqu7oPlNcO8E6Rrz-
"""

# Author: Anecia Rodriquez
# Date created: 12/10/2023
# Course: ITT103
# Purpose: An automated reservation system to assign seats on UCC Signature Express Limited luxury executive coach buses.

#Initialize variables
FIRST_CLASS_ROWS = 9
BUSINESS_CLASS_ROWS = 7
ECONOMY_CLASS_ROWS = 14
FIRST_CLASS_COLS = 3
BUSINESS_CLASS_COLS = 8
ECONOMY_CLASS_COLS = 4

# Seat array for each bus class
first_class_seats = [[''] * FIRST_CLASS_COLS for _ in range(FIRST_CLASS_ROWS)]
business_class_seats = [[''] * BUSINESS_CLASS_COLS for _ in range(BUSINESS_CLASS_ROWS)]
economy_class_seats = [[''] * ECONOMY_CLASS_COLS for _ in range(ECONOMY_CLASS_ROWS)]


# Prompt user to enter their name
First_name = input("Enter your fist name: ")
Last_name = input("Enter your last name: ")
print("")

# Function to display bus menu
def display_menu():
    print("UCC Signature Express Limited")
    print(" **** Ride in Luxury ****") # Tagline
    print("  First Class:   (F/f)")
    print("  Business Class:(B/b)")
    print("  Economy Class: (E/e)")
    print("  Quit or Cancel:(Q/q)")
    print("")

# Function to make a reservation
def make_reservation():
    class_choice = input("Please select class choice: ")
    class_choice = class_choice.lower() # accept bus class choice input in lower case

    if   class_choice == 'q':
        print("***Thank you choosing CC Signature Express Limited***")
        print("              **** Ride in Luxury ****"              )
    elif class_choice == 'f':
        seat_grid = first_class_seats
        rows = FIRST_CLASS_ROWS
        cols = FIRST_CLASS_COLS
        class_name = "First Class"
    elif class_choice == 'b':
        seat_grid = business_class_seats
        rows = BUSINESS_CLASS_ROWS
        cols = BUSINESS_CLASS_COLS
        class_name = "Business Class"
    elif class_choice == 'e':
        seat_grid = economy_class_seats
        rows = ECONOMY_CLASS_ROWS
        cols = ECONOMY_CLASS_COLS
        class_name = "Economy Class"
    else:
        print("Invalid choice!") # Output if bus class choice is not f, b, e or q
        return

    row = int(input("Enter the row number (1-{}): ".format(rows))) # store users row choice in "row"
    if row <= 0:
        print("Number must be positive or greater than zero!")
        return

    col = int(input("Enter the column number (1-{}):".format(cols))) # store users column choice in "col"
    if col <=0:
        print("Number must be positive or greater than zero!")
        return

    # Function to check if seat user selected is already reserved
    if seat_grid[row - 1][col - 1] != '': # If seat not empty, print "seat already reserved!"
        print("")
        print("Seat already reserved!")
        return

    # Function to display reserved seat row and column
    seat_grid[row - 1][col - 1] = 'X' # set element at index and print users row and column input
    print("Reserving seat: row {} column {}".format(row, col))
    print("")

    # Function to check if all seats are reserved
    if all(all(seat == 'X' for seat in row) for row in seat_grid): #if all the seats in row are reserved print " No more available seats!"
        print("")
        print("No more available seats!")

    # Display menu again
    display_menu() # repeat Display bus mean function to faciliate additional reservation

    # Function to prompt for user to input another reservation or Quit and display reservation summery
    next_choice = input("Press Enter to add another reservation or Q for reservation summery ")

    if next_choice.lower() == 'q': # If user wants to quit, display reservation summary
        total_seats = rows * cols
        reserved_seats = sum(1 for row in seat_grid for seat in row if seat == 'X')
        print("")
        print("Reservation Type:", class_name)
        print("Total number of seats:", total_seats)
        print("Total number of seats reserved:", reserved_seats)
        print("")
        print(f"***Thank you {First_name} {Last_name} for choosing CC Signature Express Limited***")
        print("                   **** Ride in Luxury ****"                                )
    else:
        make_reservation()

# Run the program
display_menu()

make_reservation()